language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t kevinh94/multi-test -f client/Dockerfile.dev client

script:
  - docker run kevinh94/multi-test npm test -- --coverage

after_success:
  # Build production files for each service
  - docker build -t kevinh94/multi-nginx nginx
  - docker build -t kevinh94/multi-client client
  - docker build -t kevinh94/multi-server server
  - docker build -t kevinh94/multi-worker worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push image to DockerHub
  - docker push kevinh94/multi-nginx
  - docker push kevinh94/multi-client
  - docker push kevinh94/multi-server
  - docker push kevinh94/multi-worker
